export const GET_LOTS_LOADING = 'GET_LOTS_LOADING';
export const GET_LOTS_FAILURE = 'GET_LOTS_FAILURE';
export const GET_LOTS_SUCCESS = 'GET_LOTS_SUCCESS';
export const GET_LOT_LOADING = 'GET_LOT_LOADING';
export const GET_LOT_FAILURE = 'GET_LOT_FAILURE';
export const GET_LOT_SUCCESS = 'GET_LOT_SUCCESS';

export const VEHICLES_REQUEST = 'VEHICLES_REQUEST';
export const VEHICLES_SUCCESS = 'VEHICLES_SUCCESS';
export const VEHICLES_FAILURE = 'VEHICLES_FAILURE';
export const VEHICLES_SET = 'VEHICLES_SET';
export const VEHICLES_CLEAR = 'VEHICLES_CLEAR';
export const VEHICLE_ADD_REQUEST = 'VEHICLE_ADD_REQUEST';
export const VEHICLE_ADD_SUCCESS = 'VEHICLE_ADD_SUCCESS';
export const VEHICLE_ADD_FAILURE = 'VEHICLE_ADD_FAILURE';
export const VEHICLE_EDIT_REQUEST = 'VEHICLE_EDIT_REQUEST';
export const VEHICLE_EDIT_SUCCESS = 'VEHICLE_EDIT_SUCCESS';
export const VEHICLE_EDIT_FAILURE = 'VEHICLE_EDIT_FAILURE';
export const VEHICLE_DELETE_REQUEST = 'VEHICLE_DELETE_REQUEST';
export const VEHICLE_DELETE_SUCCESS = 'VEHICLE_DELETE_SUCCESS';
export const VEHICLE_DELETE_FAILURE = 'VEHICLE_DELETE_FAILURE';

export const AUTH_LOGIN_REQUEST = 'AUTH_LOGIN_REQUEST';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE';
export const AUTH_AUTHENTICATE_REQUEST = 'AUTH_AUTHENTICATE_REQUEST';
export const AUTH_AUTHENTICATE_SUCCESS = 'AUTH_AUTHENTICATE_SUCCESS';
export const AUTH_AUTHENTICATE_FAILURE = 'AUTH_AUTHENTICATE_FAILURE';
export const AUTH_REGISTER_REQUEST = 'AUTH_REGISTER_REQUEST';
export const AUTH_REGISTER_SUCCESS = 'AUTH_REGISTER_SUCCESS';
export const AUTH_REGISTER_FAILURE = 'AUTH_REGISTER_FAILURE';
export const AUTH_UPDATE_REQUEST = 'AUTH_UPDATE_REQUEST';
export const AUTH_UPDATE_SUCCESS = 'AUTH_UPDATE_SUCCESS';
export const AUTH_UPDATE_FAILURE = 'AUTH_UPDATE_FAILURE';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_CHANGE_PASSWORD_REQUEST = 'AUTH_CHANGE_PASSWORD_REQUEST';
export const AUTH_CHANGE_PASSWORD_SUCCESS = 'AUTH_CHANGE_PASSWORD_SUCCESS';
export const AUTH_CHANGE_PASSWORD_FAILURE = 'AUTH_CHANGE_PASSWORD_FAILURE';
export const AUTH_FORGOT_PASSWORD_REQUEST = 'AUTH_CHANGE_PASSWORD_REQUEST';
export const AUTH_FORGOT_PASSWORD_SUCCESS = 'AUTH_CHANGE_PASSWORD_SUCCESS';
export const AUTH_FORGOT_PASSWORD_FAILURE = 'AUTH_CHANGE_PASSWORD_FAILURE';

export const AUTH_DELETE_ACCOUNT_REQUEST = 'AUTH_DELETE_ACCOUNT_REQUEST';
export const AUTH_DELETE_ACCOUNT_SUCCESS = 'AUTH_DELETE_ACCOUNT_SUCCESS';
export const AUTH_DELETE_ACCOUNT_FAILURE = 'AUTH_DELETE_ACCOUNT_FAILURE';


export const CARDS_SET = 'CARDS_SET';
export const CARDS_CLEAR = 'CARDS_CLEAR';
export const CARDS_REQUEST = 'CARDS_REQUEST';
export const CARDS_SUCCESS = 'CARDS_SUCCESS';
export const CARDS_FAILURE = 'CARDS_FAILURE';
export const CARD_ADD_REQUEST = 'CARD_ADD_REQUEST';
export const CARD_ADD_SUCCESS = 'CARD_ADD_SUCCESS';
export const CARD_ADD_FAILURE = 'CARD_ADD_FAILURE';
export const CARD_DELETE_REQUEST = 'CARD_DELETE_REQUEST';
export const CARD_DELETE_SUCCESS = 'CARD_DELETE_SUCCESS';
export const CARD_DELETE_FAILURE = 'CARD_DELETE_FAILURE';
export const CARD_SETDEFAULT_REQUEST = 'CARD_SETDEFAULT_REQUEST';
export const CARD_SETDEFAULT_SUCCESS = 'CARD_SETDEFAULT_SUCCESS';
export const CARD_SETDEFAULT_FAILURE = 'CARD_SETDEFAULT_FAILURE';

export const SESSIONS_REQUEST = 'SESSIONS_REQUEST';
export const SESSIONS_SUCCESS = 'SESSIONS_SUCCESS';
export const SESSIONS_FAILURE = 'SESSIONS_FAILURE';
export const SESSION_HISTORY_REQUEST = 'SESSION_HISTORY_REQUEST';
export const SESSION_HISTORY_SUCCESS = 'SESSION_HISTORY_SUCCESS';
export const SESSION_HISTORY_FAILURE = 'SESSION_HISTORY_FAILURE';
export const START_SESSION_REQUEST = 'START_SESSION_REQUEST';
export const START_SESSION_SUCCESS = 'START_SESSION_SUCCESS';
export const START_SESSION_FAILURE = 'START_SESSION_FAILURE';
export const END_SESSION_REQUEST = 'END_SESSION_REQUEST';
export const END_SESSION_SUCCESS = 'END_SESSION_SUCCESS';
export const END_SESSION_FAILURE = 'END_SESSION_FAILURE';
export const EXTEND_SESSION_REQUEST = 'EXTEND_SESSION_REQUEST';
export const EXTEND_SESSION_SUCCESS = 'EXTEND_SESSION_SUCCESS';
export const EXTEND_SESSION_FAILURE = 'EXTEND_SESSION_FAILURE';

export const RESOURCE_GET_REQUEST = 'RESOURCE_GET_REQUEST';
export const RESOURCE_GET_SUCCESS = 'RESOURCE_GET_SUCCESS';
export const RESOURCE_GET_FAILURE = 'RESOURCE_GET_FAILURE';

export const NOTIFICATION_ADD = 'NOTIFICATION_ADD';
export const NOTIFICATION_REMOVE = 'NOTIFICATION_REMOVE';

export const SESSION_CHANGE_VEHICLE_REQUEST = 'SESSION_CHANGE_VEHICLE_REQUEST';
export const SESSION_CHANGE_VEHICLE_SUCCESS = 'SESSION_CHANGE_VEHICLE_SUCCESS';
export const SESSION_CHANGE_VEHICLE_FAILURE = 'SESSION_CHANGE_VEHICLE_FAILURE';

export const SESSION_AUTO_RENEW_REQUEST = 'SESSION_AUTO_RENEW_REQUEST';
export const SESSION_AUTO_RENEW_SUCCESS = 'SESSION_AUTO_RENEW_SUCCESS';
export const SESSION_AUTO_RENEW_FAILURE = 'SESSION_AUTO_RENEW_FAILURE';

export const SET_USER_LANGUAGE_REQUEST = 'SET_USER_LANGUAGE_REQUEST';
export const SET_USER_LANGUAGE_SUCCESS = 'SET_USER_LANGUAGE_SUCCESS';
export const SET_USER_LANGUAGE_FAILURE = 'SET_USER_LANGUAGE_FAILURE';

export const REACTIVATE_SIGNUP_ACCOUNT_REQUEST = 'REACTIVATE_SIGNUP_ACCOUNT_REQUEST';
export const REACTIVATE_SIGNUP_ACCOUNT_SUCCESS = 'REACTIVATE_SIGNUP_ACCOUNT_SUCCESS';
export const REACTIVATE_SIGNUP_ACCOUNT_FAILURE = 'REACTIVATE_SIGNUP_ACCOUNT_FAILURE';

export const ACCOUNT_REACTIVATION_REQUEST = 'ACCOUNT_REACTIVATION_REQUEST'
export const ACCOUNT_REACTIVATION_SUCCESS = 'ACCOUNT_REACTIVATION_SUCCESS'
export const ACCOUNT_REACTIVATION_FAILURE = 'ACCOUNT_REACTIVATION_FAILURE'

export const LOADER_TOGGLE = 'LOADER_TOGGLE';
