export const NavigationScreenIds = {
  MAP_SCREEN: 'MapScreenId',
  SEARCH_SCREEN: 'SearchScreenId',
  STALL_SCREEN: 'StallScreenId',
  GATE_SCREEN: 'GateScreenId',
  LOT_SCREEN: 'LotScreenId',
  PAYMENT_SCREEN: 'PaymentScreenId',
  SIDEBAR_SCREEN: 'SidebarScreenId',
  PROFILE_SCREEN: 'ProfileScreenId',
  VEHICLES_SCREEN: 'VehiclesScreenId',
  SESSIONS_SCREEN: 'SessionsScreenId',
  QR_SCANNER_SCREEN: 'QRScannerScreenId',
  LOADING_SCREEN: 'LoadingScreenId',
  SIGN_IN_SCREEN: 'SignInScreenId',
  SIGN_UP_SCREEN: 'SignUpScreenId',
  FORGOT_PASSWORD_SCREEN: 'ForgotPasswordScreenId',
  NEW_SESSION_SCREEN: 'NewSessionScreenId',
  VEHICLE_SCREEN: 'VehicleScreenId',
  PROFILE_EDIT_SCREEN: 'ProfileEditScreenId',
  CHANGE_PASSWORD_SCREEN: 'ChangePasswordScreenId',
  CREDIT_CARD_SCREEN: 'CreditCardScreenId',
  INVOICE_SCREEN: 'InvoiceScreenId',
  LOADER_SCREEN: 'LoaderScreenId',
  EXTEND_SESSION_SCREEN: 'ExtendSessionScreenId',
  CHECKOUT_SCREEN: 'CheckoutScreenId',
  OVERLAY_ITEM_PICKER_SCREEN: 'OverlayItemPickerScreenId',
  NOTIFICATION_OVERLAY_SCREEN: 'NotificationOverlayScreenId',
  TERMS_AND_CONDITIONS_SCREEN: 'TermsAndConditionsScreenId',
  OVERLAY_POPUP: 'OverlayPopupId',
  DELETE_OVERLAY: 'DeleteOverlayId',
  OVERLAY_MESSAGE: 'OverlayMessageId',
  HELP_SUPPORT_SCREEN: 'HelpSupportId',
  COUNTRY_PICKER: 'CountryPickerId',
  LANGUAGE_SCREEN: 'LanguageScreenId',
  OVERLAY_REACTIVATE_SCREEN: 'OverlayReactivateId',
  ZONEID_POPUP: 'ZoneIdPopupId',
  SESSION_OVERLAY: 'SessionOverlayId',
  RATE_OVERLAY: 'RateOverlayId',
  MAP_DIRECTION: 'MapDirectionId'
};

export const NavigationScreenNames = {
  MAP: 'MapScreen',
  SEARCH: 'SearchScreen',
  SIDEBAR: 'SidebarScreen',
  PAYMENT: 'PaymentScreen',
  PROFILE: 'ProfileScreen',
  PROFILE_EDIT: 'ProfileEditScreen',
  SESSIONS: 'SessionsScreen',
  STALLS: 'StallScreen',
  GATES: 'GateScreen',
  LOT: 'LotScreen',
  VEHICLES: 'VehiclesScreen',
  QR_SCANNER: 'QrScannerScreen',
  LOADING: 'LoadingScreen',
  SIGN_IN: 'SignInScreen',
  SIGN_UP: 'SignUpScreen',
  FORGOT_PASSWORD: 'ForgotPasswordScreen',
  NEW_SESSION: 'NewSessionScreen',
  VEHICLE: 'VehicleScreen',
  CHANGE_PASSWORD: 'ChangePasswordScreen',
  CREDIT_CARD: 'CreditCardScreen',
  INVOICE: 'InvoiceScreen',
  LOADER: 'LoaderScreen',
  OVERLAY_ITEM_PICKER_SCREEN: 'OverlayItemPickerScreen',
  NOTIFICATION_OVERLAY_SCREEN: 'NotificationOverlayScreen',
  EXTEND_SESSION: 'ExtendSession',
  CHECKOUT: 'Checkout',
  TERMS_AND_CONDITIONS_SCREEN: 'TermsAndConditionsScreen',
  OVERLAY_POPUP: 'OverlayPopup',
  DELETE_OVERLAY: 'DeletePopup',
  OVERLAY_MESSAGE: 'OverlayMessage',
  HELP_SUPPORT: 'HelpSupport',
  COUNTRY_PICKER: 'CountryPicker',
  LANGUAGE_SCREEN: 'LanguageScreen',
  OVERLAY_REACTIVATE: 'OverlayReactivate',
  ZONEID_POPUP: 'ZoneIdPopup',
  SESSION_OVERLAY: 'SessionOverlay',
  RATE_OVERLAY: 'RateOverlay',
  MAP_DIRECTION: 'MapDirection'

};

export const NavigationScreens = {
  [NavigationScreenIds.MAP_SCREEN]: NavigationScreenNames.MAP,
  [NavigationScreenIds.SEARCH_SCREEN]: NavigationScreenNames.SEARCH,
  [NavigationScreenIds.PROFILE_SCREEN]: NavigationScreenNames.PROFILE,
  [NavigationScreenIds.PROFILE_EDIT_SCREEN]: NavigationScreenNames.PROFILE_EDIT,
  [NavigationScreenIds.SIDEBAR_SCREEN]: NavigationScreenNames.SIDEBAR,
  [NavigationScreenIds.PAYMENT_SCREEN]: NavigationScreenNames.PAYMENT,
  [NavigationScreenIds.SESSIONS_SCREEN]: NavigationScreenNames.SESSIONS,
  [NavigationScreenIds.VEHICLES_SCREEN]: NavigationScreenNames.VEHICLES,
  [NavigationScreenIds.QR_SCANNER_SCREEN]: NavigationScreenNames.QR_SCANNER,
  [NavigationScreenIds.SIGN_IN_SCREEN]: NavigationScreenNames.SIGN_IN,
  [NavigationScreenIds.SIGN_UP_SCREEN]: NavigationScreenNames.SIGN_UP,
  [NavigationScreenIds.FORGOT_PASSWORD_SCREEN]:NavigationScreenNames.FORGOT_PASSWORD,
  [NavigationScreenIds.NEW_SESSION_SCREEN]: NavigationScreenNames.NEW_SESSION,
  [NavigationScreenIds.STALL_SCREEN]: NavigationScreenNames.STALLS,
  [NavigationScreenIds.GATE_SCREEN]: NavigationScreenNames.GATES,
  [NavigationScreenIds.LOT_SCREEN]: NavigationScreenNames.LOT,
  [NavigationScreenIds.VEHICLE_SCREEN]: NavigationScreenNames.VEHICLE,
  [NavigationScreenIds.CHANGE_PASSWORD_SCREEN]:NavigationScreenNames.CHANGE_PASSWORD,
  [NavigationScreenIds.CREDIT_CARD_SCREEN]: NavigationScreenNames.CREDIT_CARD,
  [NavigationScreenIds.INVOICE_SCREEN]: NavigationScreenNames.INVOICE,
  [NavigationScreenIds.LOADER_SCREEN]: NavigationScreenNames.LOADER,
  [NavigationScreenIds.EXTEND_SESSION_SCREEN]:NavigationScreenNames.EXTEND_SESSION,
  [NavigationScreenIds.CHECKOUT_SCREEN]: NavigationScreenNames.CHECKOUT,
  [NavigationScreenIds.OVERLAY_ITEM_PICKER_SCREEN]:NavigationScreenNames.OVERLAY_ITEM_PICKER_SCREEN,
  [NavigationScreenIds.NOTIFICATION_OVERLAY_SCREEN]:NavigationScreenNames.NOTIFICATION_OVERLAY_SCREEN,
  [NavigationScreenIds.TERMS_AND_CONDITIONS_SCREEN]:NavigationScreenNames.TERMS_AND_CONDITIONS_SCREEN,
  [NavigationScreenIds.OVERLAY_POPUP]:NavigationScreenNames.OVERLAY_POPUP,
  [NavigationScreenIds.DELETE_OVERLAY]: NavigationScreenNames.DELETE_OVERLAY,
  [NavigationScreenIds.OVERLAY_MESSAGE]: NavigationScreenNames.OVERLAY_MESSAGE,
  [NavigationScreenIds.ZONEID_POPUP]: NavigationScreenNames.ZONEID_POPUP,
  [NavigationScreenIds.HELP_SUPPORT_SCREEN]: NavigationScreenNames.HELP_SUPPORT,
  [NavigationScreenIds.COUNTRY_PICKER]: NavigationScreenNames.COUNTRY_PICKER,
  [NavigationScreenIds.LANGUAGE_SCREEN]: NavigationScreenNames.LANGUAGE_SCREEN,
  [NavigationScreenIds.OVERLAY_REACTIVATE_SCREEN]: NavigationScreenNames.OVERLAY_REACTIVATE,
  [NavigationScreenIds.SESSION_OVERLAY]: NavigationScreenNames.SESSION_OVERLAY,
  [NavigationScreenIds.RATE_OVERLAY]: NavigationScreenNames.RATE_OVERLAY,
  [NavigationScreenIds.MAP_DIRECTION]: NavigationScreenNames.MAP_DIRECTION,
};

export const NavigationIds = {
  SIDE_MENU: 'SideMenuId',
  BOTTOM_TABS: 'BottomTabsId',
  AUTH: 'Auth',
  ...NavigationScreenIds,
};

export const NavigationButtonIds = {};
